### ISSUE TITLE
Some queries using limit() hang if returned result would be less than the limit.

### ISSUE THREAD

**Issue by loganSims** [WSDOT/social-analytics#1]
mongoDB v2.6.12 

The queries in [mentionsFromDate()](https://github.com/WSDOT/social-analytics/blob/80dac4ec5406d4ea0f6d1ade5ba8449d7a49d9a3/server/node/controllers/summary.js#L142) have this behavior. A work around is already in place but would like a more permanent solution. 

This issue seems to be fixed when using mongoDB v3.2.3.

**Comment by waynedyck** [comment]
I'm looking into what would be involved and any potential issues with doing an in place upgrade of our mongoDB instance.

**Comment by waynedyck** [comment]
Stale issue. Closing for now.
